// src/services/pdf/pdf-config.ts
export const PDF_CONFIG = {
    colors: {
        primary: '#0891b2',
        primaryLight: '#e0f2fe',
        background: '#f1f5f9',
        text: '#1e293b',
        textMuted: '#475569',
        textLight: '#64748b',
        border: '#e2e8f0',
        success: '#059669',
        successLight: '#ecfdf5',
        danger: '#dc2626',
        dark: '#0f172a',
        white: '#ffffff',
        footerText: '#94a3b8',
        auditHash: '#34d399',
        rowAlt: '#f8fafc',
    },
    layout: {
        pageWidth: 595,
        pageHeight: 842,
        leftMargin: 40,
        contentWidth: 515,
        headerHeight: 50,
    },
    fonts: {
        regular: 'Regular',
        bold: 'Bold',
        mono: 'Mono',
    },
    sizes: {
        title: 16,
        subtitle: 11,
        header: 9,
        normal: 8,
        small: 7.5,
        tiny: 7,
        micro: 6,
    },
    dimensions: {
        partyBoxWidth: 248,
        partyBoxHeight: 80,
        partyBoxGap: 19,
        metadataHeight: 26,
        summaryBoxWidth: 180,
        summaryBoxHeight: 22,
        summaryOffsetX: 180,
        signatureLineY: 20,
        footerTargetY: 720,
        pageBreakThreshold: 650,
        pageBreakSoft: 680,
        auditHeaderHeight: 50,
        auditPartyBoxHeight: 66,
        auditSectionHeaderHeight: 16,
        auditRowHeight: 18,
        auditDeclarationHeight: 45,
        auditHashBoxHeight: 24,
        auditUserAgentHeight: 28,
        auditLabelWidth: 200,
    },
} as const;

export const CONTRACT_CONFIG = {
    colors: {
        primary: '#059669',
        primaryLight: '#ecfdf5',
        background: '#f1f5f9',
        text: '#1e293b',
        textMuted: '#475569',
        textLight: '#64748b',
        border: '#e2e8f0',
        dark: '#0f172a',
        white: '#ffffff',
        footerText: '#94a3b8',
        auditHash: '#34d399',
        rowAlt: '#f8fafc',
        headerSubtext: '#d1fae5',
        successBorder: '#a7f3d0',
        successText: '#065f46',
        successSubtext: '#047857',
    },
    layout: {
        pageWidth: 595,
        pageHeight: 842,
        leftMargin: 40,
        contentWidth: 515,
        headerHeight: 50,
    },
    fonts: {
        regular: 'Regular',
        bold: 'Bold',
        mono: 'Mono',
    },
    sizes: {
        title: 16,
        subtitle: 11,
        header: 9,
        normal: 8,
        small: 7.5,
        tiny: 7,
        micro: 6,
    },
    dimensions: {
        partyBoxWidth: 248,
        partyBoxHeight: 90,
        partyBoxGap: 19,
        metadataHeight: 26,
        summaryBoxWidth: 180,
        summaryBoxHeight: 22,
        summaryOffsetX: 180,
        signatureLineY: 20,
        footerTargetY: 720,
        pageBreakThreshold: 680,
        auditHeaderHeight: 50,
        auditSummaryHeight: 55,
        auditPartyBoxHeight: 66,
        auditSectionHeaderHeight: 16,
        auditRowHeight: 18,
        auditDeclarationHeight: 45,
        auditHashBoxHeight: 24,
        auditUserAgentHeight: 28,
        auditSignatureBoxHeight: 90,
        auditLabelWidth: 200,
        auditSignatureWidth: 250,
        auditSignatureHeight: 80,
        headerRightX: 340,
        headerRightW: 215,
        metadataColumns: 4,
    },
} as const;

export type PDFConfig = typeof PDF_CONFIG;
export type ContractConfig = typeof CONTRACT_CONFIG;